// <auto-generated />
using System;
using BioTranan.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioTranan.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230416115927_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("BioTranan.Shared.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfTickets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BioTranan.Shared.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvalibleTickets")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ShowDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TheaterId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("BioTranan.Shared.Theater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 65,
                            Name = "Salong 1"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 80,
                            Name = "Salong 2"
                        });
                });

            modelBuilder.Entity("Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgeLimit")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxViews")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PremiereYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeLimit = 18,
                            Cast = "Marlon Brando, Al Pacino, James Caan",
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            Director = "Francis Ford Coppola",
                            Duration = 175,
                            Genre = 2,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
                            Language = "English",
                            MaxViews = 1,
                            PremiereYear = 1972,
                            Title = "The Godfather",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 2,
                            AgeLimit = 16,
                            Cast = "Tim Robbins, Morgan Freeman, Bob Gunton",
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Director = "Frank Darabont",
                            Duration = 142,
                            Genre = 2,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg",
                            Language = "English",
                            MaxViews = 10,
                            PremiereYear = 1994,
                            Title = "The Shawshank Redemption",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 3,
                            AgeLimit = 14,
                            Cast = "Christian Bale, Heath Ledger, Aaron Eckhart",
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Director = "Christopher Nolan",
                            Duration = 152,
                            Genre = 0,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg",
                            Language = "English",
                            MaxViews = 10,
                            PremiereYear = 2008,
                            Title = "The Dark Knight",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 4,
                            AgeLimit = 12,
                            Cast = "Tom Hanks, Robin Wright, Gary Sinise",
                            Description = "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
                            Director = "Robert Zemeckis",
                            Duration = 142,
                            Genre = 2,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYWY2MjE2NGQtZGNiMy00NThkLTlhZTAtMjFkNGMyMGJiZTJiXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
                            Language = "English",
                            MaxViews = 10,
                            PremiereYear = 1994,
                            Title = "Forrest Gump",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 5,
                            AgeLimit = 14,
                            Cast = "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
                            Director = "Christopher Nolan",
                            Duration = 148,
                            Genre = 0,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjExMjkwNTQ0Nl5BMl5BanBnXkFtZTcwNTY0OTk1Mw@@._V1_.jpg",
                            Language = "English",
                            MaxViews = 10,
                            PremiereYear = 2010,
                            Title = "Inception",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 6,
                            AgeLimit = 18,
                            Cast = "John Travolta, Uma Thurman, Samuel L. Jackson",
                            Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            Director = "Quentin Tarantino",
                            Duration = 154,
                            Genre = 0,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
                            Language = "English",
                            MaxViews = 10,
                            PremiereYear = 1994,
                            Title = "Pulp Fiction",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 7,
                            AgeLimit = 15,
                            Cast = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Duration = 136,
                            Genre = 0,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
                            Language = "English",
                            MaxViews = 10,
                            PremiereYear = 1999,
                            Title = "The Matrix",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 8,
                            AgeLimit = 18,
                            Cast = "Brad Pitt, Diane Kruger, Eli Roth",
                            Description = "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
                            Director = "Quentin Tarantino",
                            Duration = 153,
                            Genre = 0,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
                            Language = "English, German, French, Italian",
                            MaxViews = 10,
                            PremiereYear = 2009,
                            Title = "Inglourious Basterds",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 9,
                            AgeLimit = 18,
                            Cast = "Robert De Niro, Ray Liotta, Joe Pesci",
                            Description = "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
                            Director = "Martin Scorsese",
                            Duration = 146,
                            Genre = 2,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
                            Language = "English",
                            MaxViews = 10,
                            PremiereYear = 1990,
                            Title = "Goodfellas",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 10,
                            AgeLimit = 18,
                            Cast = "Brad Pitt, Edward Norton, Helena Bonham Carter",
                            Description = "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
                            Director = "David Fincher",
                            Duration = 139,
                            Genre = 2,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
                            Language = "English",
                            MaxViews = 10,
                            PremiereYear = 1999,
                            Title = "Fight Club",
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("BioTranan.Shared.Booking", b =>
                {
                    b.HasOne("BioTranan.Shared.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("BioTranan.Shared.Show", b =>
                {
                    b.HasOne("Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioTranan.Shared.Theater", "Theater")
                        .WithMany()
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Theater");
                });
#pragma warning restore 612, 618
        }
    }
}
